# Generated by Django 4.0.5 on 2022-06-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('IdTipoProducto', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TipoProducto',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=500)),
                ('Correo', models.CharField(max_length=30)),
                ('Contrasena', models.CharField(max_length=30)),
                ('IdTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Imagen', models.ImageField(upload_to='img/products/')),
                ('IdTipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
    ]
